version: '2.2'

services: 
    node:
      build: ./node
      container_name: "node-server"
      user: "node"
      volumes:
        - ./node/app:/home/node/app
        - /node/app/node_modules
      ports: 
        - "3000:3000"
      environment:
        NODE_ENV: development

    # react-frontend:
    #   build: ./react
    #   container_name: "react"
    #   user: "node"
    #   volumes:
    #     - ./react/frontend:/home/node/app
    #     - /react/frontend/node_modules
    #   ports: 
    #     - "4000:3000"
    # environment:
    #   NODE_ENV: development

    mongo:
      image: mongo
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      volumes:
        - mongodb_data:/data/db
      ports: 
        - "27017:27017"

    mongo-express:
      image: mongo-express
      restart: always
      environment:
        ME_CONFIG_MONGODB_SERVER: mongo
        ME_CONFIG_MONGODB_PORT: 27017
        ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
        ME_CONFIG_MONGODB_AUTH_DATABASE: admin
        ME_CONFIG_MONGODB_AUTH_USERNAME: ${MONGOEXPRESS_LOGIN}
        ME_CONFIG_MONGODB_AUTH_PASSWORD: ${MONGOEXPRESS_PASSWORD}
        ME_CONFIG_BASICAUTH_USERNAME: ${MONGOEXPRESS_LOGIN}
        ME_CONFIG_BASICAUTH_PASSWORD: ${MONGOEXPRESS_PASSWORD}
        ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
        ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      depends_on:
        - mongo
      ports:
        - 8081:8081
        
volumes:
  dbdata:
  mongodb_data:
    driver: local